name: Build Skyblock Mod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v4

      # Set up JDK 17
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # Install Gradle 8.3 system-wide (required by Loom)
      - name: Install Gradle
        run: |
          wget https://services.gradle.org/distributions/gradle-8.3-bin.zip
          sudo unzip -d /opt/gradle gradle-8.3-bin.zip
          sudo ln -s /opt/gradle/gradle-8.3/bin/gradle /usr/bin/gradle
          gradle --version

      # Build the mod
      - name: Build Mod
        run: gradle build --no-daemon

      # Upload artifact
      - uses: actions/upload-artifact@v4
        with:
          name: skyblock-mod
          path: build/libs/
          
