name: Build Skyblock Mod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - uses: actions/checkout@v4

      # 2. Set up Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 3. Install Gradle system-wide
      - name: Install Gradle
        run: |
          sudo apt-get update
          sudo apt-get install -y gradle

      # 4. Build the mod using system Gradle
      - name: Build Mod
        run: gradle build --no-daemon

      # 5. Upload the JAR artifact
      - name: Upload Mod Artifact
        uses: actions/upload-artifact@v4
        with:
          name: skyblock-mod
          path: build/libs/
          
