name: Build Skyblock Mod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Set up JDK 17
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # Install Gradle 
      - name: Build Mod
        run: gradle build --no-daemon
  
      # Verify Gradle version
      - name: Gradle Version
        run: gradle --version

      # Build the mod
      - name: Build Mod
        run: gradle build --no-daemon

      # Upload artifact
      - uses: actions/upload-artifact@v4
        with:
          name: skyblock-mod
          path: build/libs/
          
